on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docs/**'
      - '.github/*.md'
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docs/**'
      - '.github/*.md'
    branches: ["main", "dev"]

name: Validate Code
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}/src
    steps:
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Tests
      run: |
        go install github.com/jstemmer/go-junit-report@latest
        go mod tidy && go test -v ./... | go-junit-report -set-exit-code > report.xml
    - name: Test Summary
      uses: test-summary/action@v2.1
      with:
        paths: |
          src/report.xml
      if: always()
    - name: Tests Report 
      uses: dorny/test-reporter@v1
      with:
        name: Golang Tests
        path: src/report.xml
        reporter: java-junit
        fail-on-error: true
      if: always()